const $=s=>document.querySelector(s);
let comfyReady=false,workflows=[],selected=null,imageData=null,conversations=loadJSON("lva_conversations",{}),library=loadJSON("lva_library",[]);
const kinds={image:["Image","🖼️"],retouch:["Retouche","✨"],video:["Vidéo","🎬"],"video-heavy":["Vidéo lourd","🎞️"]};
function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem("lva_conversations",JSON.stringify(conversations));localStorage.setItem("lva_library",JSON.stringify(library))}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2300)}
async function api(url,opt){const r=await fetch(url,opt);const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||"Erreur");return d}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function isReady(w){return !!w.ready}
function renderModels(filter=""){const box=$("#models");box.innerHTML="";const chat={id:"__chat__",name:"Chat",kind:"chat",icon:"◌",node_count:0,ready:true};const all=[chat,...workflows];all.filter(w=>w.name.toLowerCase().includes(filter.toLowerCase())).forEach(w=>{const [label,ico]=kinds[w.kind]||["Conversation","◌"];const b=document.createElement("button");b.className="model"+(selected?.id===w.id?" active":"");b.innerHTML='<span class="active-dot"></span><span class="ico">'+(w.icon||ico)+'</span><span class="model-text"><b>'+esc(w.name)+'</b><small>'+label+'</small></span><i class="ready-dot '+(isReady(w)?"ready":"")+'"></i>';b.onclick=()=>selectWorkflow(w);box.appendChild(b)})}
function renderLibraryCounts(){let p=library.filter(x=>x.kind==="image").length,v=library.filter(x=>x.kind==="video").length,r=library.filter(x=>x.kind==="retouch").length;$("#photoCount").textContent=p||"";$("#videoCount").textContent=v||"";$("#retouchCount").textContent=r||""}
function selectWorkflow(w){selected=w;$("#modelSearch").value="";renderModels();if(w.kind==="chat"){showConversation("__chat__","Chat");return}showConversation(w.id,w.name)}
function conversationFor(id){if(!conversations[id])conversations[id]={messages:[],started:false};return conversations[id]}
function showConversation(id,name){const c=conversationFor(id);$("#welcome").classList.toggle("hidden",c.messages.length>0);const box=$("#messages");box.innerHTML="";c.messages.forEach(m=>renderMessage(m));if(c.messages.length)scrollBottom()}
function renderMessage(m){const wrap=document.createElement("div");wrap.className="message "+(m.role==="user"?"user":"assistant");if(m.text){const b=document.createElement("div");b.className="bubble";b.textContent=m.text;wrap.appendChild(b)}if(m.loading){const f=document.createElement("div");f.className="generation-frame loading";f.dataset.loading="1";f.innerHTML='<div class="loader"></div>';wrap.appendChild(f)}if(m.result){const f=document.createElement("div");f.className="generation-frame";const src=resultUrl(m.result);const video=/\.(mp4|webm|mov|mkv)$/i.test(m.result.filename||"");f.innerHTML=video?'<video class="result-media" controls src="'+src+'"></video>':'<img class="result-media" src="'+src+'">';wrap.appendChild(f)}$("#messages").appendChild(wrap);return wrap}
function resultUrl(x){return "/api/view?filename="+encodeURIComponent(x.filename||"")+"&subfolder="+encodeURIComponent(x.subfolder||"")+"&type="+encodeURIComponent(x.type||"output")}
function scrollBottom(){const c=$("#chat");requestAnimationFrame(()=>c.scrollTop=c.scrollHeight)}
function addMessage(id,m){const c=conversationFor(id);c.messages.push(m);c.started=true;save();$("#welcome").classList.add("hidden");renderMessage(m);scrollBottom()}
function setLoading(id,on){const c=conversationFor(id);const last=c.messages[c.messages.length-1];if(last?.loading===on)return;last.loading=on;save();const frames=$("#messages").querySelectorAll(".generation-frame");if(on){renderMessage(last);scrollBottom()}else{frames.forEach(f=>{if(f.dataset.loading==="1")f.remove()})}}
function addLibrary(result,kind,prompt){const item={...result,kind,prompt,createdAt:new Date().toISOString()};library.unshift(item);save();renderLibraryCounts()}
function renderLibrary(kind,title){$("#welcome").classList.add("hidden");$("#messages").innerHTML="";const box=document.createElement("div");box.className="library-view";box.innerHTML='<button class="library-back" id="libraryBack">← Retour au chat</button><h2>'+esc(title)+'</h2><div class="library-grid"></div>';$("#messages").appendChild(box);const grid=box.querySelector(".library-grid");const rows=library.filter(x=>x.kind===kind);if(!rows.length){grid.innerHTML='<div class="empty-library">Aucune création enregistrée ici.</div>';return}rows.forEach(x=>{const c=document.createElement("div");c.className="library-card";const src=resultUrl(x);const video=/\.(mp4|webm|mov|mkv)$/i.test(x.filename||"");c.innerHTML=(video?'<video controls src="'+src+'"></video>':'<img src="'+src+'">')+'<div class="meta">'+esc(x.prompt||"Création")+'</div>';grid.appendChild(c)});$("#libraryBack").onclick=()=>selectWorkflow(selected||{id:"__chat__",name:"Chat",kind:"chat",ready:true})}
async function generate(){if(!selected||selected.kind==="chat"){toast("Sélectionne un modèle de création.");return}const prompt=$("#prompt").value.trim();if(!prompt){return}const modelId=selected.id;addMessage(modelId,{role:"user",text:prompt});$("#prompt").value="";$("#prompt").style.height="";if(imageData){/* kept for the request */}const placeholder=conversationFor(modelId);placeholder.messages.push({role:"assistant",loading:true});save();renderMessage(placeholder.messages[placeholder.messages.length-1]);scrollBottom();$("#generate").disabled=true;try{const d=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workflow:modelId,prompt,negative:"",image:imageData?.data||null,image_name:imageData?.name||null})});await waitResult(d.prompt_id,modelId,prompt)}catch(e){removeLoading(modelId);addMessage(modelId,{role:"assistant",text:"Erreur : "+e.message});toast(e.message)}finally{$("#generate").disabled=false}}
function removeLoading(id){const c=conversationFor(id);c.messages=c.messages.filter(m=>!m.loading);save();$("#messages").querySelectorAll(".generation-frame[data-loading='1']").forEach(x=>x.parentElement.remove())}
async function waitResult(pid,modelId,prompt){for(let i=0;i<900;i++){await new Promise(r=>setTimeout(r,1000));try{const d=await api("/api/history/"+encodeURIComponent(pid)),h=d[pid];if(!h)continue;if(h.status?.status_str==="error"||h.status?.status_str==="failed"){removeLoading(modelId);addMessage(modelId,{role:"assistant",text:"La génération a échoué."});return}if(h.outputs){let found=null;let outKind="image";for(const o of Object.values(h.outputs)){if(o.images?.length){found=o.images[0];outKind="image";break}if(o.gifs?.length){found=o.gifs[0];outKind="video";break}}if(found){removeLoading(modelId);const c=conversationFor(modelId);c.messages.push({role:"assistant",result:found});c.started=true;save();renderMessage(c.messages[c.messages.length-1]);scrollBottom();const wk=workflows.find(x=>x.id===modelId);addLibrary(found,wk?.kind==="retouch"?"retouch":outKind,prompt);return}}}catch(e){}}removeLoading(modelId);addMessage(modelId,{role:"assistant",text:"La génération prend plus de temps que prévu."})}
function showSidebar(){document.querySelector(".sidebar").classList.remove("closed")}
function hideSidebar(){document.querySelector(".sidebar").classList.add("closed")}
async function refresh(){try{const h=await api("/api/health");$("#statusText").textContent=h.online?"ComfyUI connecté":"ComfyUI arrêté";$(".status").className="status "+(h.online?"ok":"bad")}catch(e){$("#statusText").textContent="Moteur indisponible";$(".status").className="status bad"}const d=await api("/api/workflows");workflows=d.workflows.map(w=>({...w,ready:comfyReady}))renderModels($("#modelSearch").value);if(!selected)selectWorkflow({id:"__chat__",name:"Chat",kind:"chat",ready:true});else renderModels($("#modelSearch").value);renderLibraryCounts()}
function setup(){$("#openSidebar").onclick=showSidebar;$("#closeSidebar").onclick=hideSidebar;$("#modelSearch").oninput=e=>renderModels(e.target.value);$("#generate").onclick=generate;$("#prompt").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();generate()}});$("#prompt").addEventListener("input",e=>{e.target.style.height="auto";e.target.style.height=Math.min(e.target.scrollHeight,220)+"px"});$("#attachBtn").onclick=()=>$("#imageFile").click();$("#imageFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{imageData={data:r.result,name:f.name};$("#imageName").textContent=f.name;$("#imageChip").hidden=false};r.readAsDataURL(f)};$("#removeImage").onclick=()=>{imageData=null;$("#imageChip").hidden=true;$("#imageFile").value=""};$("#photosLibrary").onclick=()=>renderLibrary("image","Mes photos générées");$("#videosLibrary").onclick=()=>renderLibrary("video","Mes vidéos générées");$("#retouchLibrary").onclick=()=>renderLibrary("retouch","Mes retouches générées");$("#importBtn").onclick=()=>$("#workflowFile").click();$("#workflowFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const wf=JSON.parse(await f.text());await api("/api/import-workflow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.name,workflow:wf})});toast("Workflow ajouté.");await refresh()}catch(err){toast(err.message)}};$("#comfyBtn").onclick=()=>window.open("http://127.0.0.1:8188","_blank");refresh()}setup();