const $=s=>document.querySelector(s);let workflows=[],selected=null,imageData=null;
const kinds={image:["Image","🖼️"],retouch:["Retouche","✨"],video:["Vidéo","🎬"],"video-heavy":["Vidéo lourd","🎞️"]};
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
async function api(url,opt){const r=await fetch(url,opt);const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||"Erreur");return d}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderModels(){const box=$("#models");box.innerHTML="";workflows.forEach(w=>{const [label,ico]=kinds[w.kind]||["Workflow","⚙️"];const b=document.createElement("button");b.className="model"+(selected?.id===w.id?" active":"");b.innerHTML='<span class="ico">'+(w.icon||ico)+'</span><span><b>'+esc(w.name)+'</b><small>'+label+'</small></span>';b.onclick=()=>selectWorkflow(w);box.appendChild(b)})}
function selectWorkflow(w){selected=w;renderModels();$("#modelName").textContent=w.name;$("#modelMeta").textContent=(kinds[w.kind]?.[0]||"Workflow")+" · "+w.node_count+" nœuds";$("#modeLabel").textContent=kinds[w.kind]?.[0]||"Workflow";$("#empty").style.display=$("#gallery").children.length?"none":"flex"}
async function refresh(){try{const h=await api("/api/health");$("#statusText").textContent=h.online?"ComfyUI connecté":"ComfyUI arrêté";$(".status").className="status "+(h.online?"ok":"bad")}catch(e){$("#statusText").textContent="Moteur indisponible";$(".status").className="status bad"}const d=await api("/api/workflows");workflows=d.workflows;renderModels();if(!selected&&workflows.length)selectWorkflow(workflows[0])}
function addResult(item){$("#empty").style.display="none";const c=document.createElement("div");c.className="card";const file=item.filename,sub=item.subfolder||"",type=item.type||"output";const src="/api/view?filename="+encodeURIComponent(file)+"&subfolder="+encodeURIComponent(sub)+"&type="+encodeURIComponent(type);const isVideo=/\.(mp4|webm|mov|mkv)$/i.test(file);c.innerHTML=(isVideo?'<video controls src="'+src+'"></video>':'<img src="'+src+'" loading="lazy">')+'<div class="cap">'+esc(file)+'</div>';$("#gallery").prepend(c)}
async function generate(){if(!selected){toast("Choisis un workflow.");return}const prompt=$("#prompt").value.trim();if(!prompt){toast("Décris ce que tu veux créer.");return}$("#generate").disabled=true;$("#generate").textContent="…";try{const d=await api("/api/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({workflow:selected.id,prompt,negative:"",image:imageData?.data||null,image_name:imageData?.name||null})});toast("Génération lancée.");await waitResult(d.prompt_id)}catch(e){toast(e.message)}finally{$("#generate").disabled=false;$("#generate").textContent="↑"}}
async function waitResult(pid){for(let i=0;i<900;i++){await new Promise(r=>setTimeout(r,1000));try{const d=await api("/api/history/"+encodeURIComponent(pid)),h=d[pid];if(!h)continue;if(h.status?.status_str==="error"||h.status?.status_str==="failed"){toast("La génération a échoué.");return}if(h.outputs){let count=0;Object.values(h.outputs).forEach(o=>(o.images||[]).forEach(x=>{addResult(x);count++}));Object.values(h.outputs).forEach(o=>(o.gifs||[]).forEach(x=>{addResult(x);count++}));if(count){toast("Génération terminée.");return}}}catch(e){}}toast("La génération prend plus de temps que prévu.")}
function setup(){$("#generate").onclick=generate;$("#prompt").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();generate()}});$("#newChat").onclick=()=>{$("#gallery").innerHTML="";$("#empty").style.display="flex";$("#prompt").value="";imageData=null;$("#imageChip").hidden=true};$("#attachBtn").onclick=()=>$("#imageFile").click();$("#imageFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{imageData={data:r.result,name:f.name};$("#imageName").textContent=f.name;$("#imageChip").hidden=false};r.readAsDataURL(f)};$("#removeImage").onclick=()=>{imageData=null;$("#imageChip").hidden=true;$("#imageFile").value=""};$("#importBtn").onclick=()=>$("#workflowFile").click();$("#workflowFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const wf=JSON.parse(await f.text());await api("/api/import-workflow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.name,workflow:wf})});toast("Workflow ajouté.");await refresh()}catch(err){toast(err.message)}};$("#comfyBtn").onclick=()=>window.open("http://127.0.0.1:8188","_blank");document.querySelectorAll(".suggestions button").forEach(b=>b.onclick=()=>{const p=b.dataset.preset;if(p==="import")$("#workflowFile").click();else{const w=workflows.find(x=>p==="heavy"?x.kind==="video-heavy":p==="video"?x.kind==="video":x.kind==="image");if(w)selectWorkflow(w)}});refresh()}setup();